### ISSUE TITLE
Allow to use wildcards in path

### ISSUE THREAD

**Issue by zlorf** [jharding/grunt-sed#14]
It would be nice if sed allow to use wildcards and other goodies available in most of grunt tasks (http://gruntjs.com/configuring-tasks#globbing-patterns), for example:

```
sed:
    all_api_url:
        path: "build/**/*.{js,html}"
        pattern: '%API%'
        replacement: "<%= config.api_url %>"
```

For now it fails: `Warning: ENOENT, no such file or directory`.
